"""empty message

Revision ID: 1ee95e8b78d2
Revises: f0691e10eab7
Create Date: 2022-01-12 17:49:16.159284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee95e8b78d2'
down_revision = 'f0691e10eab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular__activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=25), nullable=False),
    sa.Column('activity', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['state_name'], ['states.state'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('popular__activities')
    # ### end Alembic commands ###
