"""empty message

Revision ID: 33cff4f6e439
Revises: b48511722d01
Create Date: 2022-01-18 11:46:37.456090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cff4f6e439'
down_revision = 'b48511722d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('album', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['album'], ['albums.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('photo_albums')
    op.add_column('journal_entries', sa.Column('trip', sa.Text(), nullable=False))
    op.drop_column('journal_entries', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('journal_entries', 'trip')
    op.create_table('photo_albums',
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='photo_albums_user_fkey'),
    sa.PrimaryKeyConstraint('title', name='photo_albums_pkey')
    )
    op.drop_table('photos')
    op.drop_table('albums')
    # ### end Alembic commands ###
