"""empty message

Revision ID: 3a756504218f
Revises: 4674a378f8eb
Create Date: 2022-01-30 20:08:24.137607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a756504218f'
down_revision = '4674a378f8eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('entry', sa.Text(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('journal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal'], ['journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
