"""empty message

Revision ID: 4674a378f8eb
Revises: a6c76f4e6488
Create Date: 2022-01-30 20:01:14.114364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4674a378f8eb'
down_revision = 'a6c76f4e6488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entry', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('journal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['journal'], ['journal.id'], name='journal_entries_journal_fkey')
    )
    # ### end Alembic commands ###
