"""empty message

Revision ID: 4ad5d8a000de
Revises: 1ee95e8b78d2
Create Date: 2022-01-12 18:23:20.149872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad5d8a000de'
down_revision = '1ee95e8b78d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state__attractions', sa.Column('att_loc', sa.String(length=50), nullable=True))
    op.drop_column('state__attractions', 'att_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state__attractions', sa.Column('att_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('state__attractions', 'att_loc')
    # ### end Alembic commands ###
