"""empty message

Revision ID: 516db17e6263
Revises: 87522b9599a0
Create Date: 2022-01-11 20:49:48.413450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516db17e6263'
down_revision = '87522b9599a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'population')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
