"""empty message

Revision ID: 614752239e20
Revises: 87cccfb2f341
Create Date: 2022-01-24 18:06:29.904492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614752239e20'
down_revision = '87cccfb2f341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_albums',
    sa.Column('album', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('num_of_pics', sa.String(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('album')
    )
    op.add_column('user', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_added')
    op.drop_table('photo_albums')
    # ### end Alembic commands ###
