"""empty message

Revision ID: 778d415304d1
Revises: 
Create Date: 2022-01-08 15:37:15.192593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778d415304d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('state_name', sa.String(length=25), nullable=False),
    sa.Column('state_abbr', sa.String(length=5), nullable=True),
    sa.Column('nickname', sa.String(length=150), nullable=True),
    sa.Column('flag', sa.String(length=300), nullable=True),
    sa.Column('capital', sa.String(length=150), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=25), nullable=True),
    sa.Column('largest_city', sa.String(length=150), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('state_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('states')
    # ### end Alembic commands ###
