"""empty message

Revision ID: 87522b9599a0
Revises: 
Create Date: 2022-01-11 20:43:40.132603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87522b9599a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('state', sa.String(length=25), nullable=False),
    sa.Column('state_abbr', sa.String(length=5), nullable=True),
    sa.Column('nickname', sa.String(length=150), nullable=True),
    sa.Column('flag', sa.String(length=300), nullable=True),
    sa.Column('capital', sa.String(length=150), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=25), nullable=True),
    sa.Column('largest_city', sa.String(length=150), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('apitoken', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('state__attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=25), nullable=False),
    sa.Column('attraction', sa.String(length=200), nullable=True),
    sa.Column('att_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['state_name'], ['states.state'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visited_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=25), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_name'], ['states.state'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visited_states')
    op.drop_table('state__attractions')
    op.drop_table('user')
    op.drop_table('states')
    # ### end Alembic commands ###
