"""empty message

Revision ID: cbd0e2556eee
Revises: f353ef39edec
Create Date: 2022-01-09 15:05:15.652488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd0e2556eee'
down_revision = 'f353ef39edec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apitoken', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apitoken')
    # ### end Alembic commands ###
