"""empty message

Revision ID: dc4ddcef5c5e
Revises: 614752239e20
Create Date: 2022-01-25 20:31:28.219296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc4ddcef5c5e'
down_revision = '614752239e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('num_of_entries', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('num_of_pics', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('journal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal'], ['journal.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('photo_albums')
    op.add_column('journal_entries', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('journal_entries', sa.Column('date_added', sa.DateTime(), nullable=False))
    op.add_column('journal_entries', sa.Column('journal', sa.Integer(), nullable=False))
    op.drop_constraint('journal_entries_user_fkey', 'journal_entries', type_='foreignkey')
    op.create_foreign_key(None, 'journal_entries', 'journal', ['journal'], ['id'])
    op.drop_column('journal_entries', 'trip')
    op.drop_column('journal_entries', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('journal_entries', sa.Column('trip', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.create_foreign_key('journal_entries_user_fkey', 'journal_entries', 'user', ['user'], ['id'])
    op.drop_column('journal_entries', 'journal')
    op.drop_column('journal_entries', 'date_added')
    op.drop_column('journal_entries', 'id')
    op.create_table('photo_albums',
    sa.Column('album', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('num_of_pics', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name='photo_albums_user_fkey'),
    sa.PrimaryKeyConstraint('album', name='photo_albums_pkey')
    )
    op.drop_table('albums')
    op.drop_table('journal')
    # ### end Alembic commands ###
