"""empty message

Revision ID: eacf5bdac8d2
Revises: f19b2a921115
Create Date: 2022-01-10 17:36:11.204313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacf5bdac8d2'
down_revision = 'f19b2a921115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apitoken', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apitoken')
    # ### end Alembic commands ###
