"""empty message

Revision ID: f19b2a921115
Revises: cbd0e2556eee
Create Date: 2022-01-10 17:35:41.395738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19b2a921115'
down_revision = 'cbd0e2556eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apitoken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apitoken', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
