"""empty message

Revision ID: f353ef39edec
Revises: 778d415304d1
Create Date: 2022-01-08 15:44:22.707629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f353ef39edec'
down_revision = '778d415304d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state__attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=25), nullable=True),
    sa.Column('attraction', sa.String(length=200), nullable=True),
    sa.Column('att_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visited_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=25), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state'], ['states.state_name'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visited_states')
    op.drop_table('state__attractions')
    # ### end Alembic commands ###
